#!/bin/bash
set -euo pipefail

if [[ "$(arch)" == "aarch64" ]]; then
  arch="arm64"
else
  arch="amd64"
fi

plugin=${BUILDKITE_PLUGINS:-""}
repo="https://github.com/com6056/monorepo-diff-buildkite-plugin"
executable="monorepo-diff-buildkite-plugin-linux-${arch}"
test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"
url=${repo}/releases/latest/download/${executable}

if [[ "$test_mode" == "false" ]]; then
  echo ${url}
  curl -Lf -o ${executable} $url && chmod +x ${executable}
fi

./${executable}
