name: Publish

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Check quality
        run: make quality

      - name: Build the binary (linux-amd64)
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          ARCH: "amd64"
          OS: "linux"

      - name: Build the binary (linux-arm64)
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          ARCH: "arm64"
          OS: "linux"

      - name: Build the binary (linux-ppc64le)
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          ARCH: "ppc64le"
          OS: "linux"

      - name: Build the binary (darwin-amd64)
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          ARCH: "amd64"
          OS: "darwin"

      - name: Build the binary (darwin-arm64)
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          ARCH: "arm64"
          OS: "darwin"

      - name: Upload the binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: monorepo-diff-buildkite-plugin-*-*
